### ISSUE TITLE
Thanks for using PyTorch-Ignite !

### ISSUE THREAD

**Issue by vfdev-5** [nussl/nussl#160]
Hey @pseeth @ethman 

Recently find out your repository where you are using Ignite for train/eval of the DL models. 
As being one of Ignite's core team, I'm pleased to see its spread out :) Thanks for using it 👍 
If you, guys, have a feedback on the lib, would like to contribute some common features or need a support for some functionalities, please, do not hesitate to reach out us on github, pytorch discuss forum or pytorch slack. 

I'm closing this issue as it's not one :)

**Comment by pseeth** [comment]
Thanks for checking us out! Yeah Ignite is really nice and was a breeze to use. Thanks for giving me something I didn't have to put under full test coverage! Every feature I looked for was pretty much there, or it was easy to attach a handler to it. 

I noticed you have a list of projects that use Ignite on the Ignite readme. Feel free to add us if you like as an example, as this would be the only audio one on the list, I think.

**Comment by vfdev-5** [comment]
Thanks for this nice feedback !

> I noticed you have a list of projects that use Ignite on the Ignite readme. Feel free to add us if you like as an example, as this would be the only audio one on the list, I think.

@pseeth yes, I forgot to ask you that. Definitly, I'll add your repository there !
