### ISSUE TITLE
nussl installation

### ISSUE THREAD

**Issue by dev-101** [nussl/nussl#163]
Hi, I'm trying to install **nussl** under Ubuntu 20.04, but always get something in the way.

Under Ubuntu 20.04 I had issues with pip, because python2 is no longer present, so after manually installing it with pip (via curl), I received this error for ffmpy:

> Downloading ffmpy-0.2.3.tar.gz
> ERROR: Could not find a version that satisfies the requirements termtables (from nussl) (from versions: none)

Which Ubuntu version should be the most compatible with nussl? Should I try Ubuntu 18.04?
I am trying to make it work for quite some time and still can't.
Thanks!

---

Installed on Ubuntu 18.04 via git clone. It seems that this project is not updated for 20.04

**Comment by pseeth** [comment]
Hey, just saw this got closed. What needs to be changed to install on Ubuntu 20.04? `nussl` doesn't support Python 2 anymore, only Python 3. But it should work unless something drastic changed between Ubuntu installations, which doesn't totally make sense to me. You can also try installing `nussl` in a `conda` environment with Python > 3.6, which should work

**Comment by dev-101** [comment]
Hi, thanks for your reply. Well, a month ago I installed it in Ubuntu 18.04 virtual machine, and somehow it passed without major issues (a warning that python2 support deprecation when I installed pip). But, now I tried to do it in 20.04 and failed when got to step to install dependencies (requirements.txt).

Here's the steps I use(d):

Ubuntu 18.04:

>sudo apt-add-repository universe
sudo apt update
sudo apt upgrade
sudo apt install python (this does not work in 20.04, so I used sudo apt install python3)
sudo apt install python-pip (or sudo apt install python3-pip)
pip install --upgrade pip

then:

>this fails for some reason, so I use git (next paragraph)
pip install nussl
cd nussl
pip install -r requirements.txt

this worked:

>sudo apt install git
git clone https://github.com/nussl/nussl
cd nussl
pip install -r requirements.txt
pip install -r extra_requirements.txt

test:

>sudo apt install python-logilab-common
sudo apt install pytest (or sudo apt install python-pytest)
pytest

for Ubuntu 20.04 I tried once this, but later failed at ffmpy as described):

>sudo apt install python2
sudo apt install curl
curl https://bootstrap.pypa.io/get-pip.py --output get-pip.py
sudo python2 get-pip.py

However, now I realized I don't know what to do next... I just wish to import some pretrained model and do basic tests on few wav files. I have to find something less complicated or learn other things first.

**Comment by pseeth** [comment]
Gotcha, I'm wondering why you're installing Python 2 though? When you should be using Python 3? I'll look into 20.04 when I get time though and try it out. It also seems you're installing a lot of Python stuff via sudo apt which shouldn't be needed. For a working sequence of commands, you can look at how we test `nussl` on a fresh Ubuntu machine here: https://github.com/nussl/nussl/blob/master/.github/workflows/tests.yml

For using pre-trained models, you can start here for a snippet: https://nussl.github.io/docs/examples/deep/deep_clustering.html

We'll be adding more pre-trained models soon for other separation tasks.

Hope this helps!

**Comment by dev-101** [comment]
Hi, thank you very much for your help! I haven't forgotten about this, I'm just in the middle of something atm, so I will try it from scratch and hopefully it will work. I found also a demo page with examples, so it will be a good start (hopefully).

Thanks again!
