### ISSUE TITLE
HPSS object has no attribute interact

### ISSUE THREAD

**Issue by Silur** [nussl/nussl#190]
## Issue description
Running the code in the README produces an error:
```python
>>> import nussl
>>> nussl.separation.primitive.HPSS(nussl.AudioSignal()).interact(share=True)

AttributeError: 'HPSS' object has no attribute 'interact'
```
## Env info

- Python 3.8.6 (default, Sep 30 2020, 04:00:38)
- GCC 10.2.0
- NumPy 1.19.2
- SciPy 1.5.2
- nussl 1.1.1

## Additional info
First I thought maybe the HPSS constructor returns `None` but checking directly confirms it simply doesn't have the documented field:
```python
>>> asd = nussl.separation.primitive.HPSS(nussl.AudioSignal())
>>> asd
HPSS on AudioSignal (unlabeled): [unknown] sec @ path unknown, 44100 Hz, 1 ch.
>>> type(asd)
<class 'nussl.separation.primitive.hpss.HPSS'>
>>> asd.__dict__
{'_audio_signal': <nussl.core.audio_signal.AudioSignal object at 0x7fcd42decfd0>, '_mask_type': <class 'nussl.core.masks.soft_mask.SoftMask'>, '_mask_threshold': 0.5, 'result_masks': [], 'kernel_size': 31}
```

**Comment by ethman** [comment]
Hey! Sorry about that! This feature is in nussl version 1.1.3, which I just pushed to PyPI. You can get this feature now by running `pip install nussl==1.1.3` in your active conda environment.

Let me know if this works.

**Comment by Silur** [comment]
1.1.3 works, closing :+1:
